// src/app/pujasData.js

export const PUJAS = [
  {
    id: "1",
    slug: "ganesh-puja",
    name: "Ganesh Puja",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/ganesh-puja.jpg",
  },
  {
    id: "2",
    slug: "laghrudra-abhishek",
    name: "Laghrudra Abhishek",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 25,000",
    offlinePrice: "₹ 41,000",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "4–5 hours",
    image: "/images/LaghrudraAbhishek.jpg",
  },
  {
    id: "3",
    slug: "vastu-shanti-puja",
    name: "Vastu Shanti Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 11,000",
    offlinePrice: "₹ 31,000",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/vastu-shanti-puja.png",
  },
  {
    id: "4",
    slug: "bhoomi-puja",
    name: "Bhoomi Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/bhumipuja.png",
  },
  {
    id: "5",
    slug: "satyanarayan-puja",
    name: "Satyanarayan Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,500",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/satyanarayan.jpg",
  },
  {
    id: "6",
    slug: "lakshmi-puja",
    name: "Lakshmi Prapti Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 2,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/laxmi.jpg",
  },
  {
    id: "7",
    slug: "shiv-puja",
    name: "Shiv Puja / Rudrabhishek",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/rudraabhishek.jpg",
  },
  {
    id: "8",
    slug: "durga-puja",
    name: "Durga Puja",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 2,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/Durga_Puja.jpg",
  },  
  {
    id: "9",
    slug: "vishnu-puja",
    name: "Vishnu Puja",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/vishnupuja.jpg",
  },
  {
    id: "10",
    slug: "rahu-ketu-shanti-puja",
    name: "Rahu–Ketu Shanti Puja",
    category: "Astrology",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 5,100",
    offlinePrice: "₹ 11,000",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "3–4 hours",
    image: "/images/rahu-ketu-shanti.png",
  },
  {
    id: "11",
    slug: "navagraha-shanti-puja",
    name: "Navagraha Shanti Puja",
    category: "Astrology",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/Navgraha.jpg",
  },
  {
    id: "12",
    slug: "shani-shanti-puja",
    name: "Shani Shanti Puja",
    category: "Astrology",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 2,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/shanishanti.jpg",
  },
  {
    id: "13",
    slug: "mangal-dosh-nivaran",
    name: "Mangal Dosh Nivaran",
    category: "Astrology",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 2,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/mangaldosh.jpg",
  },
  {
    id: "14",
    slug: "kaal-sarp-dosh-puja",
    name: "Kaal Sarp Dosh Shanti Puja",
    category: "Astrology",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/kaalsarp.jpg",
  },
  {
    id: "15",
    slug: "maha-mrityunjaya-havan",
    name: "Mahamrityunjaya Mantra Jaap for Health & Protection",
    category: "Havan Ceremonies",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "2–3 hours",
    image: "/images/Maha_Mrityunjaya_Jaap.jpg",
  },
  {
    id: "16",
    slug: "gayatri-havan",
    name: "Gayatri Havan",
    category: "Havan Ceremonies",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/gayatripuja.jpg",
  },
  {
    id: "17",
    slug: "dhan-prapti-havan",
    name: "Dhan Prapti Havan",
    category: "Havan Ceremonies",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/dhanprapti.jpg",
  },
  {
    id: "18",
    slug: "sarva-badha-nivaran-havan",
    name: "Sarva Badha Nivaran Havan",
    category: "Havan Ceremonies",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/vastu.jpeg",
  },
    {
    id: "19",
    slug: "shanti-havan",
    name: "Naugraha Shanti Havan",
    category: "Havan Ceremonies",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/LakshmiNarayanYagya.jpg",
  },
  {
    id: "20",
    slug: "rudraabhishek",
    name: "Rudrabhishek Puja for Wish Fulfillment",
    category: "Havan & Special",
    shortDescription:
      "Lord Shiva puja for fulfillment of wishes, peace, prosperity and spiritual growth.",
    onlinePrice: "₹ 2,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/rudraabhishek.jpg",
  },
  // {
  //   id: "21",
  //   slug: "durga-puja-2",
  //   name: "Durga Puja",
  //   category: "Havan & Special",
  //   shortDescription:
  //     "Sacred fire ritual for purification, health and spiritual upliftment.",
  //   onlinePrice: "₹ 2,100",
  //   offlinePrice: "₹ 3,100",
  //   onlineAvailable: true,
  //   offlineAvailable: true,
  //   duration: "1–2 hours",
  //   image: "/images/Durga_Puja.jpg",
  // },
  {
    id: "22",
    slug: "saraswati-puja",
    name: "Saraswati Puja",
    category: "Havan & Special",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/saraswati-puja.jpg",
  },
  // {
  //   id: "23",
  //   slug: "navagraha-shanti",
  //   name: "Navagraha Shanti",
  //   category: "Havan & Special",
  //   shortDescription:
  //     "Sacred fire ritual for purification, health and spiritual upliftment.",
  //   onlinePrice: "₹ 1,100",
  //   offlinePrice: "₹ 2,100",
  //   onlineAvailable: true,
  //   offlineAvailable: true,
  //   duration: "1–2 hours",
  //   image: "/images/vastu.jpeg",
  // },
  {
    id: "24",
    slug: "maha-mrityunjaya-jaap",
    name: "Maha Mrityunjaya Jaap",
    category: "Daily Puja",
    shortDescription:
      "ONE DAY maha mrityunjaya jaap for health, protection and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 3,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/Maha_Mrityunjaya_Jaap.jpg",
  },
  {
    id: "25",
    slug: "sundarKand-path",
    name: "SundarKand Path",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/SundarKandPath.jpg",
  },
  {
    id: "26",
    slug: "hanuman-chalisa-path",
    name: "Hanuman Chalisa Path",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/Hanuman-Ji.jpg",
  },
  {
    id: "27",
    slug: "ramayan-path",
    name: "Ramayan Path",
    category: "Havan & Special",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 4,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/akhand-ramayan-path.jpg",
  },
    {
    id: "28",
    slug: "nauchandi-path",
    name: "9 Chandi Path",
    category: "Havan & Special",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 5,100",
    offlinePrice: "₹ 11,000",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/nauchandi.jpg",
  },
  // {
  //   id: "29",
  //   slug: "rahu-ketu-shanti",
  //   name: "Rahu Ketu Shanti",
  //   category: "Havan & Special",
  //   shortDescription:
  //     "Sacred fire ritual for purification, health and spiritual upliftment.",
  //   onlinePrice: "₹ 3,100",
  //   offlinePrice: "₹ 5,100",
  //   onlineAvailable: true,
  //   offlineAvailable: true,
  //   duration: "1–2 hours",
  //   image: "/images/rahu-ketu-shanti.png",
  // },
  {
    id: "30",
    slug: "bhoomi-pujan-construction-site-puja",
    name: "Bhoomi Pujan / Construction Site Puja",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: false,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/office.jpg",
  },
  {
    id: "31",
    slug: "atharvashirsha-path",
    name: "Atharvashirsha Path",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,500",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/ganesh-puja.jpg",
  },
  {
    id: "32",
    slug: "kanakdhara-path",
    name: "Kanakdhara Path",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,500",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/kanakdhara.jpg",
  },
  {
    id: "33",
    slug: "business-growth",
    name: "Shri Sukt Path for Job & Business Growth",
    category: "Daily Puja",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/kanakdhara.jpg",
  },
  {
    id: "34",
    slug: "grah-klesh-nivaran",
    name: "Grah Klesh Nivaran / Lakshmi Narayan Puja Yagya",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 2,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/griha.jpg",
  },
  {
    id: "35",
    slug: "shatru-nivaran-baglamukhi-puja",
    name: "Shatru Nivaran Baglamukhi Puja / Havan",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 4,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/Baglamukhi.jpg",
  },
  {
    id: "36",
    slug: "satya-narayan-katha",
    name: "Satya Narayan Katha",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/satyanarayan.jpg",
  },
  {
    id: "37",
    slug: "griha-pravesh-puja",
    name: "Griha Pravesh Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 1,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/griha.jpg",
  },
  {
    id: "38",
    slug: "pittra-dosh-nivaran-tripindi-shradh",
    name: "Pittra Dosh Nivaran Tripindi Shradh",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 0",
    offlinePrice: "₹ 21,000",
    onlineAvailable: false,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/PitraDoshNivaran.jpg",
  },
  {
    id: "39",
    slug: "kumbha-vivah-puja",
    name: "Kumbha Vivah Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/kumbhvivah.png",
  },
  {
    id: "40",
    slug: "ark-vivah-puja",
    name: "Ark Vivah Puja",
    category: "Home / Auspicious",
    shortDescription:
      "Sacred fire ritual for purification, health and spiritual upliftment.",
    onlinePrice: "₹ 3,100",
    offlinePrice: "₹ 5,100",
    onlineAvailable: true,
    offlineAvailable: true,
    duration: "1–2 hours",
    image: "/images/arkvivah.png",
  },
];